// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyAUb34zPv2yFYc9nlqRGNWzhib72OX1o',
    appId: '1:1088754075559:android:375488648b848582fe5882',
    messagingSenderId: '1088754075559',
    projectId: 'epregnancy-2022',
    databaseURL: 'https://epregnancy-2022-default-rtdb.firebaseio.com',
    storageBucket: 'epregnancy-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMiYGULcLjHA_ZgUgoHPQjZJGjZj76YYY',
    appId: '1:1088754075559:ios:87b40468266b0272fe5882',
    messagingSenderId: '1088754075559',
    projectId: 'epregnancy-2022',
    databaseURL: 'https://epregnancy-2022-default-rtdb.firebaseio.com',
    storageBucket: 'epregnancy-2022.appspot.com',
    androidClientId: '1088754075559-5stpefsc162kju798pfsjiobuqdhnsuv.apps.googleusercontent.com',
    iosClientId: '1088754075559-5ff8dod4c93tc129f99sk127mjkpm5e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.pregnancyApp',
  );
}
